### ISSUE TITLE
Investigate the recent 100% cpu spike on AWS

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#794] opened 2024-03-26 10:16 UTC

**Comment by samschlicht** [comment] 2024-03-28 02:58
Here are the big spikes last week. I'm focusing on the 100% one but thought I should highlight all, just in case they have anything in common.

- 100% - 21 March, 21:10 UTC
- 73% - 26 March, 02:30 UTC
- 75% - 26 March, 03:55 UTC

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--644d61d7d54b9f06c994af40bfd2abeefb5b2c25/Screenshot%202024-03-28%20at%201.53.58%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 1.53.58 pm.png" />
<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1VaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ba03e63e156e88a201aac240a045ab4bcc21be0/Screenshot%202024-03-28%20at%201.54.38%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 1.54.38 pm.png" />
<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1laQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51a1265c7002e17226ef442876031484081b2b4d/Screenshot%202024-03-28%20at%201.54.27%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 1.54.27 pm.png" />

**Comment by samschlicht** [comment] 2024-03-28 03:02
Just having a look in [Cloudwatch](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-anomalies) and see that we have an option to switch on [Log anomaly detection](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/LogsAnomalyDetection.html). Looks like it's free and would add some vigilance for unusual log patterns.

**Comment by samschlicht** [comment] 2024-03-28 03:45
This is the instance that went down: \b33e59f50b4f4f049f10a6cc7198f14c

But most of the activity and errors at that time are from the other (\989ce365fac742bd9fd48f542a6047cf) and seem to involve file-upload/form-data (the times you're seeing here allow for Melbourne time difference to UTC):
<img width="1515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9aQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20780bd176b281293e54476dde0b7c822219f2fc/Screenshot%202024-03-28%20at%202.42.11%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 2.42.11 pm.png" />

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDBaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61bb11ebc455d9e93fb367338c5ebd3c693613ec/Screenshot%202024-03-28%20at%202.46.28%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 2.46.28 pm.png" />

<img width="1390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--833428e24eb0f4f93b865235007aef8b5d1a502f/Screenshot%202024-03-28%20at%202.47.27%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 2.47.27 pm.png" />

**Comment by samschlicht** [comment] 2024-03-28 04:02
Candidate #229186 Isamar Tabares was registering at that moment — she appears to have been kicked out of her account because shortly after receiving her thank-you email she requests a password-reset link.


<img width="1391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d615729bd30f4d3d48698aba792561d19d43c1ee/Screenshot%202024-03-28%20at%202.53.30%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 2.53.30 pm.png" />


Interestingly, she has successfully uploaded an attachment, but only many hours later, and it's a word docx containing images that hasn't fared too well (attached). Perhaps just a coincidence but I'll have a play with some candidate portal upload scenarios.

[HOJA DE VIDA ISAMAR CENTER (2).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--576637dcc279596878ae6c0be8a7d90d9a15dbf8/HOJA%20DE%20VIDA%20ISAMAR%20CENTER%20%282%29.docx)

**Comment by samschlicht** [comment] 2024-03-28 04:13
This is the last registered activity on the instance that went down, the same file-upload/form-data issue:

<img width="1515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0618520f036c9bdf3fdc0b6e7aa9d2f97117e1a4/Screenshot%202024-03-28%20at%203.13.04%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 3.13.04 pm.png" />

Here are the principal errors in text form:

- org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. java.io.EOFException
- at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:127) ~[spring-web-5.3.28.jar:5.3.28]
- Caused by: java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. java.io.EOFException

**Comment by samschlicht** [comment] 2024-03-28 04:20
There's not much admin activity at that time, it looks like an issue with a candidate form submission that included a file upload, but I can't glean much more from what's at hand.

I checked the other two spikes but I don't see similar errors — they appear to relate to admin searches.

**Comment by samschlicht** [comment] 2024-03-28 05:15
Just for reference, I was able to reproduce the error in question by uploading a file on the candidate portal and then closing my browser window. But there was no CPU spike, so perhaps that's a red herring!
<img width="1509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29aQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--889e134c674b29c892c4b947e5422da399d885d7/Screenshot%202024-03-28%20at%204.14.31%E2%80%AFpm.png" alt="Screenshot 2024-03-28 at 4.14.31 pm.png" />

Just curious that it happened so many times around the CPU spike.

**Comment by samschlicht** [comment] 2024-04-11 00:47
@sadatmalik I've reviewed this and I think the reference in your ongoing profiling issue is sufficient — at this stage, no reason to think that the fileupload connection is anything more than a one-time coincidence. Closing this one per your suggestion.

**Closed as completed by samschlicht** 2024-04-11 00:47 UTC
