### ISSUE TITLE
Error message enhancement 

### ISSUE THREAD

**Issue by hiba-machfej** [talentbeyondboundaries/tbbtalentv2#1398] opened 2024-09-23 12:50 UTC
Trying to create a new user, if the user name is already taken it gives this error.
<img width="1205" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEgwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bbd17926633e3f31a1294e0cf68f892d145a2cc/Screenshot%202024-09-23%20at%203.44.15%E2%80%AFPM.png" alt="Screenshot 2024-09-23 at 3.44.15 PM.png" />
 
Maybe it can be enhanced to something like:
"Error: Username is already taken."
"Oops! It looks like that username is unavailable. Please choose a different one."

**Comment by EhsanEhrari** [comment] 2024-10-29 07:48
@hiba-machfej I couldn't reproduce this one could you please let me know how did you produce this?

As you see in the screenshot below, I created an account with the same username and got an informative error message.

<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlY5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d00a350855259e1b111dd35d8e6dccd329e416e/image.png" alt="image.png" />

**Comment by EhsanEhrari** [comment] 2024-10-31 05:36
I will close this because Me and @hiba-machfej couldn't reproduce it again, It maybe happened when Hiba was first trying to work with DB so maybe the error was showing before the DB was set correctly.

**Closed as completed** 2024-11-07 05:52 UTC
