### ISSUE TITLE
Candidate job offer contracts should be uploadable from the Candidate Opportunity screen on the TC

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#149] opened 2023-07-06 03:45 UTC
As an Talent Catalog user I need to be able to quickly locate a candidate's contract for a particular job

**Comment by sadatmalik** [comment] 2023-11-14 10:06
Possible duplicate of #286

**Comment by sadatmalik** [comment] 2023-12-05 09:17
Closed with #286

**Closed as completed by sadatmalik** 2023-12-05 09:17 UTC
Labels: enhancement
