### ISSUE TITLE
Job creator can indicate that they are only interested in reviewing candidates they have added

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1698] opened 2024-11-29 05:06 UTC
Suggestion from Zeynep and Mariam:

> We should add a checkbox to the job registration for employers to indicate whether they want source partners to search for candidates or if the employer only wants to proceed with the candidates they've added.
> 
> As a source partner, when an employer registers a new job, I want to understand very clearly what the employer is asking of me.

Any destination partner (including employer access) may want to nominate suggested candidates only. Relevant to autonomous access as well - where the candidate is fixed.

**Comment by samschlicht** [comment] 2024-12-12 01:18
Duplicate of #1638

**Closed as completed by samschlicht** 2024-12-12 01:18 UTC
