### ISSUE TITLE
SF staging sandbox

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#169] opened 2023-07-13 09:06 UTC

**Comment by samschlicht** [comment] 2023-08-10 03:20
@camerojo steps so far:
- Logged into SF sandbox (Prod SF > Setup > Sandboxes)
- Setup > Apps > App Manager
- Replicated prod connection settings except for the root URL and digital certificate, which was generated using this command: openssl req -x509 -newkey rsa:1024 -nodes -keyout key.pem -out cert.pem -days 36500 -subj "/O=Talent Catalog/CN=www.tctalent-test.org/"
- Next, we need to point the test app at the SF staging sandbox (application.yaml / terraform.tfvars ?), using the new private key

**Comment by samschlicht** [comment] 2023-08-10 03:52
Logging a Q/concern - there are files such as...
 
- ui/admin-portal/src/app/model/base.ts /  
- ui/admin-portal/src/app/services/salesforce.service.ts
- server/src/main/java/org/tbbtalent/server/util/SalesforceHelper.java
- server/src/main/java/org/tbbtalent/server/model/sf/SalesforceObjectBase.java

...that use the SF root URL, which is different for the sandbox. This may be a tricky aspect of making this work.

**Comment by samschlicht** [comment] 2023-08-10 05:35
[ ] update configuration JSON on AWS test

**Comment by samschlicht** [comment] 2023-08-10 05:59
- [ ] Once happy with all the above steps, the next will be to test that connection to SF prod still works by including the env var in the TEST AWS JSON
- [ ] Assuming that it does, remove it, then add it to a new PROD AWS JSON

We should then be confident that we have a working SF Sandbox connection in TC dev and test, and a working SF Prod connection in TC prod.

**Comment by samschlicht** [comment] 2023-08-14 09:52
To see SF client id Setup > App Manager > right-hand arrow > 'View' > 'Manage Consumer Details'

**Comment by samschlicht** [comment] 2023-08-17 08:57
move client_id to tbb_secrets etc instead of in version control

**Comment by samschlicht** [comment] 2023-08-21 02:42
Deleted my previous comments because I'm using quite a different approach than initially planned.

Rather than create a new SF connected app, I'm able to use the existing 'tbbtalent' SF _connected app_ that TC prod is using for connection to SF prod. The same credentials work for my sandbox user to gain access to the sandbox, using a different set of variables for the JWT bearer token (which obtains an access token from SF) and URLs to point to and edit/create objects in the respective environment.

I've manually edited these variables and everything's working from dev. Next steps:

- [x] use [this doc](https://docs.google.com/document/d/1jRlPRpOTjN_GgCUv-H-jL_ZsAhTrdC-V8CqjFFW0W-o/edit) (which is to track all my changes) to code the different variables for toggling per environment
- [x] transfer those variables to the tbb_secrets.txt, the task-definition on AWS prod and terraform.tfvars for TC test (staging)
- [ ] discuss with Sadat/John whether this is a good moment to add some security to the way these variables are stored

Manual tests conducted in dev:
- [x] Candidate SF link update in TC
- [x] Updated candidate info in TC (reflected to SF when changes made to candidate oppo)
- [x] Update candidate oppo in TC
- [x] Updated job oppo in TC
- [x] New job oppo from SF link creation in TC (errors for candidates that aren't in TC, but that's to be expected, I suppose) incl updates from TC syncing to SF

**Comment by samschlicht** [comment] 2023-08-21 02:48
Qs: should the doc for the variables be in application.yml or salesforceconfig.java?

**Comment by samschlicht** [comment] 2023-08-21 03:41
I'm getting this error when I interact with SF objects — although it's all working, I'll need to check what it's about...

Text: 2023-08-21 13:39:27.868 ERROR 79389 --- [nio-8080-exec-9] i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWtjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--feba0073c8c4a8131a38cd536dbce7b26c04c199/Screenshot%202023-08-21%20at%201.40.22%20pm.png)

**Comment by samschlicht** [comment] 2023-08-21 04:07
Getting a minor error saying that @Autowired should only be used in a declared Spring component
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb51de64e9ba1c3ef07afc17b0c5ca899f862303/Screenshot%202023-08-21%20at%202.06.54%20pm.png)

**Comment by samschlicht** [comment] 2023-08-21 06:29
I want to use the environment configuration files to choose the right SF url for my frontend, but just wondering which environment staging is using? We might need to choose a staging specific version and apply it on AWS/GitHub.

**Comment by samschlicht** [comment] 2023-08-21 07:07
Interested in how SF link is populated, which is all I'm getting any errors on at the moment. Guessing that's because my branch is out of date with regard to SF sync.

**Comment by samschlicht** [comment] 2023-08-22 06:07
I figured out that the simplest way to toggle to the appropriate SF url in the frontend is to use Caroline's isStagingEnv() method, i.e. `return window.location.host == 'tctalent-test.org';`. To clean up, I can turn it into a service to be used in all the frontend files that require it.

But trying to do it by using the environment/ files did lead me to some interesting learning. 
- choice of environment file is commonly used to toggle [enableProdMode()](https://v2.angular.io/docs/ts/latest/api/core/index/enableProdMode-function.html), which should be set to true whenever you're NOT debugging your application - when it's set to false, it will do a change detection pass without making lots of costly calls to server - so for staging and prod it should be set to true.
- but you can also use the environment to change other application settings such as target urls, which are then configured during the build, rather than later using any methods in the code - in future we may want to create an environment.staging.ts to replicate prod/dev except in some desired particulars.
- you then need to point to the right environment files in the angular.json file which directs the build of your various environments. [This](https://medium.com/@hongtatyew/about-environment-ts-in-your-angular-applications-50646ab08c81) was a useful article on the topic.
- the deploy yaml files then need to be edited to use env-specific frontend compile methods in build.gradle

In this case, there are a few too many considerations involved in changing all the build and deploy files, so I'll leave it for a future issue.

**Comment by samschlicht** [comment] 2023-08-28 02:42
Note that I've made new tbb_secrets.txt (dev), terraform.tfvars (staging) and task-definition.json (prod), stored locally for now, as they obviously contain secrets!

**Comment by samschlicht** [comment] 2023-09-05 02:17
I've discovered that there's a bit more to making the terraform variables work. It's not a question of syntax for them to correspond to the application.yml files - they need connecting here: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXRuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ce7c828153d92ab39d02cdae368213144ad84c62/Screenshot%202023-09-05%20at%2012.18.09%20pm.png)

**Comment by samschlicht** [comment] 2023-09-05 02:18
e.g.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXhuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4637e84af6f65d27fe585baa17b875610882e962/Screenshot%202023-09-05%20at%2012.18.39%20pm.png)

**Comment by samschlicht** [comment] 2023-09-05 02:19
Will run my understanding by the team before making any further changes

**Comment by samschlicht** [comment] 2023-09-05 02:53
Basically all the variables need listing in the main.tf and test.tf files for each environment. I've gone ahead and done that and will update my PR. Noting that intelliJ provides some nice safety when doing this, producing errors whenever any of these files are deficient.

Also noting for future that we may want to mark sensitive values as such, per [this article](https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables), which stops them being recorded in any TF logs — but we'd presumably want to run that change by Tarek.

**Comment by samschlicht** [comment] 2023-09-18 04:17
This is deployed in staging now and working fine, except for one thing that was an issue in tc-test before I deployed my branch!

Editing 'Progress' on a candidate opportunity is not possible due to an issue with the stage field:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0dwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e9db038ac63225021c4ea7b7dc3c24d271ab693c/Screenshot%202023-09-18%20at%202.13.53%20pm.png)

It works in dev and has always worked in prod. So the mystery is why it would be happening in tc-test and not elsewhere! This is what I'm getting from my browser's dev inspector:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0twIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65d3d052d324b4b8b8021af7d2328faeff7ec4d2/Screenshot%202023-09-18%20at%202.16.54%20pm.png)

**Comment by samschlicht** [comment] 2023-09-18 04:28
Okay, through further testing I've discovered that the above is not an issue when you create a new job and add candidates from tc-test, ie. new 'cases' — only for pre-existing ones created in other environments — so this isn't critical but it would be good to better understand and perhaps come up with a fix so that tc-test is a bit more user friendly?

**Comment by samschlicht** [comment] 2023-09-18 04:54
Slack DM to the TBB team (you'll find the sensitive files there):
Hi folks, merged my SF sandbox branch into staging this morning, so you’ll all need this new tbb_secrets file, and anyone wishing to Terraform staging will need the terraform.tfvars file. Please let me know who else I should send this to, or whether you’d like to do so yourselves. I’ve opted not to post it in our channel, since it’s not private.

You should also all have received an invite last week to log into our SF sandbox, which is now linked to TC dev and staging — let me know ASAP if you need this resending, as it might be a bit of a pain to get access once I go on leave!

I’ve also deployed to tc-test with the new task-definition, and it’s working fine apart from a small wrinkle which I’ve described in the issue comments (NB: not caused by my branch — I’d previously noted the same bug with regard to the pre-existing tc-test — so perhaps a candidate for a future bug fix rather than a showstopper for this issue), so I’ve gone ahead and made a new task definition for prod, which includes the new SF variables, ready for deployment at release. [tbb-task-definition:23](https://us-east-1.console.aws.amazon.com/ecs/v2/task-definitions/tbb-task-definition/23/containers?region=us-east-1)

**Closed as completed** 2023-10-03 10:05 UTC
Labels: best practice
